# Generated by Django 5.0.10 on 2026-03-25 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('SELECT', 'SELECT'), ('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('CREATE', 'CREATE TABLE/INDEX'), ('ALTER', 'ALTER'), ('DROP', 'DROP'), ('TRUNCATE', 'TRUNCATE'), ('GRANT', 'GRANT'), ('REVOKE', 'REVOKE'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CONNECT', 'Connect'), ('DISCONNECT', 'Disconnect'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('db_user', models.CharField(max_length=255)),
                ('application_name', models.CharField(blank=True, max_length=255)),
                ('client_host', models.CharField(blank=True, max_length=255)),
                ('client_port', models.IntegerField(blank=True, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=255)),
                ('table_name', models.CharField(blank=True, max_length=255)),
                ('query', models.TextField(blank=True)),
                ('query_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rows_affected', models.IntegerField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_log', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('operation_type', 'Specific Operation'), ('user_activity', 'User Activity Threshold'), ('off_hours', 'Off-Hours Access'), ('bulk_delete', 'Bulk Delete/Truncate'), ('privilege_change', 'Privilege Change'), ('failed_login', 'Failed Login Attempts'), ('sensitive_table', 'Sensitive Table Access'), ('schema_change', 'Schema Change (DDL)'), ('unusual_volume', 'Unusual Query Volume'), ('new_user', 'New/Unknown User')], max_length=50)),
                ('condition_config', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_webhook', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='audit.alertrule')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='audit.auditevent')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('connection_mode', models.CharField(choices=[('direct', 'Direct — audit server connects to DB'), ('agent', 'Agent  — remote agent pushes events here')], default='direct', max_length=10)),
                ('engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('mssql', 'SQL Server'), ('oracle', 'Oracle')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('activity_summary', 'Activity Summary'), ('user_activity', 'User Activity'), ('sensitive_access', 'Sensitive Data Access'), ('privilege_changes', 'Privilege Changes'), ('schema_changes', 'Schema Changes'), ('anomaly_report', 'Anomaly Report'), ('compliance_gdpr', 'Compliance - GDPR'), ('compliance_sox', 'Compliance - SOX'), ('compliance_hipaa', 'Compliance - HIPAA')], max_length=50)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.databaseconnection')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='auditevent',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='audit.databaseconnection'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='database',
            field=models.ForeignKey(blank=True, help_text='Null = applies to all databases', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='audit.databaseconnection'),
        ),
        migrations.CreateModel(
            name='AgentNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly name, e.g. 'prod-mysql-billing agent'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('server_host', models.CharField(help_text='IP or hostname of the server running the agent', max_length=255)),
                ('server_os', models.CharField(blank=True, max_length=100)),
                ('agent_version', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending — waiting first connection'), ('active', 'Active'), ('warning', 'Warning — delayed heartbeat'), ('offline', 'Offline'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('queue_size', models.IntegerField(default=0, help_text='Pending events in agent local queue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('database', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='audit.databaseconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['database', 'occurred_at'], name='audit_audit_databas_674217_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['db_user', 'occurred_at'], name='audit_audit_db_user_a55fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['operation', 'occurred_at'], name='audit_audit_operati_0ed24b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['table_name', 'occurred_at'], name='audit_audit_table_n_450cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['severity', 'occurred_at'], name='audit_audit_severit_5d8e3c_idx'),
        ),
    ]
